--------------------------------------------------Arrays Numby vs Listas-------------------------------------------------------------------------------

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
array= np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [4]:
lista =[1,'dois',3.0]
print(lista)

[1, 'dois', 3.0]


In [5]:
print(type(lista))

<class 'list'>


In [6]:
for elemento in lista:
    print(type(elemento))

<class 'int'>
<class 'str'>
<class 'float'>


In [7]:
import numpy as np

array=np.array(lista)
print(array)

['1' 'dois' '3.0']


In [8]:
print(type(array))

<class 'numpy.ndarray'>


In [9]:
print(array.dtype)

<U32


In [10]:
lista=[1,2,3,4,5]
nova_lista=lista+1#isso causara um erro
print(nova_lista)

TypeError: can only concatenate list (not "int") to list

In [11]:
print(lista+[1])

[1, 2, 3, 4, 5, 1]


In [12]:
nova_lista=[]

for numero in lista:
    nova_lista.append(numero+1)

print(nova_lista)

[2, 3, 4, 5, 6]


In [13]:
import numpy as np

array=np.array([1,2,3,4,5])
novo_array=array+1 #isso adicionara 1 a todos os elementos
print(novo_array)

[2 3 4 5 6]


In [14]:
import numpy as np
import time
#Crie uma lisa e um array com 10 milhçoes de números
lista=list(range(1,10_000_001))
array= np.array(range(1,10_000_001))

#Calcule a soma de todos os numeros na lista
inicio=time.time()
soma_lista=sum(lista)
fim=time.time()
print(f'Tempo para somar todos os números na lista: {fim-inicio} segundos')

#Calcule a soma de todos os números no array
inicio=time.time()
soma_array=np.sum(array)
fim=time.time()
print(f'Tempo para somar todos os números na lista: {fim-inicio} segundos')


Tempo para somar todos os números na lista: 0.06299829483032227 segundos
Tempo para somar todos os números na lista: 0.002996206283569336 segundos


--------------------------------------------------Array Explicado-------------------------------------------------------------------------------

In [16]:
import numpy as np

#Criação de um array

array=np.array(['a','b','c','d','e'])
print(array)

['a' 'b' 'c' 'd' 'e']


In [18]:
print(array[0])
print(array[1])
print(array[2])
print(array[3])
print(array[4])
print(array[-1])

a
b
c
d
e
e


In [19]:
print(array[1:4])
print(array[0:4])
print(array[0:-1])

['b' 'c' 'd']
['a' 'b' 'c' 'd']
['a' 'b' 'c' 'd']


In [20]:
print(array[0:-1:2])

['a' 'c']


In [22]:
print(array[0::2])
print(array[::2])
print(array[::])
print(array[::-1])

['a' 'c' 'e']
['a' 'c' 'e']
['a' 'b' 'c' 'd' 'e']
['e' 'd' 'c' 'b' 'a']


--------------------------------------------------Funções Basicas de Array-------------------------------------------------------------------------------

In [23]:
import numpy as np
precos=np.array([20,25,30,25,40])

novos_precos=precos*1.10
print(novos_precos)

[22.  27.5 33.  27.5 44. ]


In [24]:
import numpy as np
vendas=np.array([200,220,250,210,300])

total_vendas=np.sum(vendas)
print(total_vendas)

1180


In [25]:
import numpy as np
vendas=np.array([200,220,250,210,300])

media_vendas=np.mean(vendas)
print(media_vendas)
print(f'A média de vendas foi de R${media_vendas:.2f}')

236.0
A média de vendas foi de R$236.00


In [26]:
import numpy as np
precos=np.array([20,25,30,25,40])

produto_mais_caro=np.max(precos)
produto_mais_barato=np.min(precos)
print(produto_mais_caro,produto_mais_barato)
print(f'Produto mais caro: {produto_mais_caro}')
print(f'Produto mais barato: {produto_mais_barato}')

40 20
Produto mais caro: 40
Produto mais barato: 20


In [27]:
import numpy as np
vendas=np.array([200,220,250,210,300])

vendas_ordenadas=np.sort(vendas)
print(vendas_ordenadas)

[200 210 220 250 300]


In [30]:
import numpy as np

quantidades= np.array([10,20,30,40])

precos=np.array([5,10,15,20])

print(quantidades*precos)
print(np.sum(quantidades*precos))

[ 50 200 450 800]
1500


In [31]:
total_vendas=np.dot(quantidades,precos)
print(total_vendas)

1500


--------------------------------------------------Aleatoris e Estatisticas-------------------------------------------------------------------------------

In [32]:
import numpy as np

rng=np.random.default_rng()

numero_aleatorio=rng.random()
print(numero_aleatorio)

0.5182470467782622


In [33]:
numero_aleatorio=rng.random()*10
print(numero_aleatorio)

8.422323070891624


In [36]:
array_aleatorio=rng.random(3)
print(array_aleatorio)

[0.08640562 0.98640108 0.90098257]


In [37]:
print(array_aleatorio*10)

[0.86405618 9.86401078 9.00982569]


In [38]:
rng=np.random.default_rng(seed=42)
dados_vendas=rng.integers(low=50, high=200, size=30)
print(dados_vendas)

[ 63 166 148 115 114 178  62 154  80  64 128 196 160 164 157 167 126  69
 175 117 125 105  77 189 167 146 110 173 131 116]


In [40]:
vendas_maximas=np.max(dados_vendas)
dia_vendas_maximas=np.argmax(dados_vendas)+1
print(f'O dia com as vendas mais altas foi o dia {dia_vendas_maximas} com {vendas_maximas} vendas')

O dia com as vendas mais altas foi o dia 12 com 196 vendas


In [41]:
vendas_minimas=np.min(dados_vendas)
dia_vendas_minimas=np.argmax(dados_vendas)+1
print(f'O dia com as vendas mais baixas foi o dia {dia_vendas_minimas} com {vendas_minimas} vendas')

O dia com as vendas mais baixas foi o dia 12 com 62 vendas


In [42]:
media_vendas=np.mean(dados_vendas)
print(f'A média de vendas durante o mês foi de {media_vendas} vendas por dia.')

A média de vendas durante o mês foi de 131.4 vendas por dia.


In [43]:
#Mediana
print(np.median(dados_vendas))

129.5


In [44]:
#percentil
print(np.percentile(dados_vendas, 50))

129.5


In [45]:
#Desvio padrão
print(np.std(dados_vendas))

39.305300745149715


In [46]:
#Variância
print(np.var(dados_vendas))

1544.9066666666665


--------------------------------------------------Where no Numpy-------------------------------------------------------------------------------

In [48]:
import numpy as np

salarios = np.array([3000,3500,4000,2000,4500,4000,5000])

#calcular a média salarial
media_salarial=np.mean(salarios)

print(media_salarial)

3714.285714285714


In [49]:
#INdentificar funcionarios com salarios acima da media
funcionarios_acima_media=np.where(salarios>media_salarial)
print(funcionarios_acima_media)

(array([2, 4, 5, 6], dtype=int64),)


In [50]:
print(salarios[funcionarios_acima_media])

[4000 4500 4000 5000]


In [51]:
print(salarios>media_salarial)

[False False  True False  True  True  True]


In [52]:
print(salarios[salarios>media_salarial])

[4000 4500 4000 5000]


In [53]:
print(np.where(salarios>media_salarial,'acima da média','abaixo da média'))

['abaixo da média' 'abaixo da média' 'acima da média' 'abaixo da média'
 'acima da média' 'acima da média' 'acima da média']


In [54]:
#dar bonus de 10% para os funcionarios com salarios abaixo da media
salarios_bonus=np.where(salarios<media_salarial,salarios*1.1,salarios)
print(salarios)
print(salarios_bonus)

[3000 3500 4000 2000 4500 4000 5000]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]


In [55]:
print(np.where((salarios>=3000) & (salarios<=4500)))

(array([0, 1, 2, 4, 5], dtype=int64),)


In [57]:
salarios_ajustados=np.where((salarios>=3000) & (salarios<=4500), salarios*1.05, salarios)
print(salarios_ajustados)

[3150. 3675. 4200. 2000. 4725. 4200. 5000.]


In [58]:
print(np.where((salarios_ajustados<3000) | (salarios_ajustados>4500)))

(array([3, 4, 6], dtype=int64),)


In [59]:
salarios_ajustados=np.where((salarios<3000) | (salarios>4500), salarios_ajustados*1.1, salarios_ajustados)
print(salarios_ajustados)

[3150. 3675. 4200. 2200. 4725. 4200. 5500.]


--------------------------------------------------Reshape-------------------------------------------------------------------------------

In [61]:
import numpy as np

vendas=np.array([200,220,250,210,300,280,230,210,220,240,230,210,280,220])

vendas_reshaped=np.reshape(vendas,(2,7))
print(vendas_reshaped)

[[200 220 250 210 300 280 230]
 [210 220 240 230 210 280 220]]


In [62]:
#retorna o numero de dimensões
print(vendas.ndim)

1


In [63]:
#retorna a quantidade de elementos em cada tupla
print(vendas.shape)

(14,)


In [64]:
print(vendas_reshaped.ndim)
print(vendas_reshaped.shape)

2
(2, 7)


In [65]:
print(vendas_reshaped)

[[200 220 250 210 300 280 230]
 [210 220 240 230 210 280 220]]


In [66]:
print(vendas_reshaped[0])

[200 220 250 210 300 280 230]


In [67]:
print(vendas_reshaped[1])

[210 220 240 230 210 280 220]


In [68]:
print(vendas_reshaped[0][0])
print(vendas_reshaped[0][1])
print(vendas_reshaped[1][0])
print(vendas_reshaped[1][5])

200
220
210
280


In [69]:
print(vendas_reshaped.sum())

3300


In [70]:
#soma os elementos da primeira linha com a segunda
print(vendas_reshaped.sum(axis=0))

[410 440 490 440 510 560 450]


In [72]:
#soma os elementos da primeira linha e soma os elementos da segunda
print(vendas_reshaped.sum(axis=1))

[1690 1610]


In [73]:
print(vendas_reshaped.mean(axis=1))

[241.42857143 230.        ]
